from dotenv import load_dotenv
from test_tc01_input_data import test_tc01_input_data
from test_tc02_invalid_image_format import test_tc02_invalid_image_format
from test_tc03_invalid_image_size import test_tc03_invalid_image_size
from test_tc04_blank_on_required_input import test_tc04_blank_on_required_input
from test_tc05_insert_mandatory_data import test_tc05_insert_mandatory_data
from test_tc06_template_1_successfully_rendered import test_template_1_successfuly_rendered
from test_tc07_template_2_successfully_rendered import test_template_2_successfuly_rendered
from test_tc08_template_3_successfully_rendered import test_template_3_successfuly_rendered
from test_tc09_not_selecting_template_send_notification import test_not_selecting_template
from test_tc10_download_cv_success import test_download_cv
from test_tc11_input_valid_unique_code import test_input_valid_code
from test_tc12_input_invalid_unique_code import test_input_invalid_code
from test_tc13_edit_user_data import test_edit_user_data

load_dotenv()